kind: Deployment
apiVersion: apps/v1 
metadata:
  name: nfs-client-provisioner
  namespace: tezign-common
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner 
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner 
    spec:
      serviceAccount: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 150fb4bc01-jkd14.cn-beijing.nas.aliyuncs.com
            - name: NFS_PATH
              value: /
      volumes:
        - name: nfs-client-root
          nfs:
            server: 150fb4bc01-jkd14.cn-beijing.nas.aliyuncs.com
            path: /
