apiVersion: v1
kind: Service
metadata:
  name: zookeeper-nodeport
  namespace: kafka
spec:
  type: NodePort
  ports:
       - port: 2181
         nodePort: 32181
  selector:
    app: zookeeper
    release: kafka
